### ISSUE TITLE
Array of regular expressions 

### ISSUE THREAD

**Issue by sarahyj** [lonekorean/highlight-within-textarea#13]
Hey :) 

Can the plugin be used with an array of regular expressions? I tried and it doesn't seem to work.. Not sure if I'm doing something wrong.

**Comment by lonekorean** [comment]
Yep, should work fine. What's your code?

**Comment by sarahyj** [comment]
Never mind I wasn't using the latest update it's working fine now thank you :).

**Comment by lonekorean** [comment]
Glad to hear. :)
