### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by ange007** [lonekorean/highlight-within-textarea#14]
Hello.
Whether development of similar for Emoji is planned?
As in case of use of this plug-in, others (for example: https://github.com/mervick/emojionearea) will normally not work.

**Comment by lonekorean** [comment]
highlight-within-textarea works fine with emojis in normal textareas. It will highlight emojis as expected. The plugin you linked actually replaces the textarea with a content-editable div. Without the textarea, it's not possible to use my plugin.
