### ISSUE TITLE
highlighting miss-aligned 

### ISSUE THREAD

**Issue by graingerkid** [lonekorean/highlight-within-textarea#15]
Hey, 

I have the following code:

```
<script>
counter = function() {
  if ($(this).next('div.result').length) {
    $(this).next('div.result').remove();
  }
  var output = '<div class="result">Words: <span class="wordCount">0</span><br/> Total Characters (including trails): <span class="totalChars">0</span><br/> Characters (excluding trails): <span class="charCount">0</span><br/> Characters (excluding all spaces): <span class="charCountNoSpace">0</span></div>';

  $(this).after(output);
  var value = $(this).val();
  if (value.length == 0) {
    $(this).next('div.result').find('.wordCount').html(0);
    $(this).next('div.result').find('.totalChars').html(0);
    $(this).next('div.result').find('.charCount').html(0);
    $(this).next('div.result').find('.charCountNoSpace').html(0);
    return;
  }
  var regex = /\s+/gi;
  var wordCount = value.trim().replace(regex, ' ').split(' ').length;
  var totalChars = value.length;
  var charCount = value.trim().length;
  var charCountNoSpace = value.replace(regex, '').length;
  $(this).next('div.result').find('.wordCount').html(wordCount);
  $(this).next('div.result').find('.totalChars').html(totalChars);
  $(this).next('div.result').find('.charCount').html(charCount);
  $(this).next('div.result').find('.charCountNoSpace').html(charCountNoSpace);
};
$(document).ready(function() {
  $('#count').click(counter);
  $('.text').on('change keyup focusout blur', counter);

});
</script>
```

Basically, it counts the words on the page - this inserted below the textarea. However, the problem is it seems to miss-align the highlighting. See the following image:

![screenshot_072417_013707_pm](https://user-images.githubusercontent.com/3381276/28523630-3120d3f2-7075-11e7-9260-6027840bb8bd.jpg)

Any idea on how to fix this?

**Comment by lonekorean** [comment]
This plug-in wraps the textarea in extra divs to do its thing. I'm suspicious that `$(this).after(output);` is inserting elements into these divs and throwing things off. Test it without that line, see what happens.

Also, if you're dynamically setting text in the textarea (not sure if you are), make sure you call `$('.my-textarea').highlightWithinTextarea('update');` when you do so the highlighting can update.

Hope that helps.

**Comment by graingerkid** [comment]
Removing `$(this).after(output);` mean the output won't display.

Also, changing `$('.my-textarea').highlightWithinTextarea(onInputRegexAgain);`  to `$('.my-textarea').highlightWithinTextarea('update');` breaks it completely.

**Comment by lonekorean** [comment]
Yeah, the output wouldn't display, but it's just a temporary test to see if that is what is affecting the highlights. If so, then you'd know to change where in the DOM you render that output.

The `.highlightWithinTextarea('update')` is not a replacement for your `.highlightWithinTextarea(onInputRegexAgain)` call, you should still be calling that as you were before. But if you have some other script/code that is injecting content into the textarea directly (as in, not entered by the user) then you'd want to call `.highlightWithinTextarea('update')` at that point to update highlights.
