### ISSUE TITLE
changing the highlighted words in the textaera, jump the focus to the begining of the textarea

### ISSUE THREAD

**Issue by MrNHQ** [lonekorean/highlight-within-textarea#26]
Hello,

I noticed that when a dynamically change the highlighted words, the focus in the textarea always jump back to the begining of it. 
I have a set of ranges, on a long text.
`highlight: [
              {
                  highlight: otheIndex,
                  className: 'yellow'
              },
              {
                  highlight: currenIndex,
                  className: 'blue'
              }
          ]`

I click a button to change the range of the "currentIndex" changes but the focus of the textarea jump to the beginning. I would expect that the focus stay where the user is looking.

Could you advice?

**Comment by lonekorean** [comment]
If you change the content of a textarea via JavaScript, it will reset the position of the caret. This plug-in doesn't do that, it only highlights text (in a separate element).

Can you check that you don't have other JavaScript that is editing the content of the textarea? That is my hunch.

**Comment by MrNHQ** [comment]
Hello, 
I tried by changing it in your example and I got the same behaviour:
I scroll in the textearea and then I click on the button that I added to change de highlighted word (but not the content), it send me back to the beginning of the textarea.

codepen: https://codepen.io/MrNHQ/project/editor/AabpRp

in the "Custom Object (with Class Name)" section:
`
<section>

			<h2>Custom Object (with Class Name)</h2>

			<p>Any type mentioned here can be put in an object wrapper with <code>highlight</code> and <code>className</code> properties. This lets you set CSS classes in the highlight markup for custom styling, such as changing the highlight color.</p>
			<textarea class="class-example">Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!Here's a blueberry. There's a strawberry. Surprise, it's a banananana!</textarea>
			<p onclick="myFunction()">click me</p>
			<script>
			$('.class-example').highlightWithinTextarea({
			    highlight: [
			        {
			            highlight: 'strawberry',
			            className: 'red'
			        },
			        {
			            highlight: 'blueberry',
			            className: 'blue'
			        },
			        {
			            highlight: /ba(na)*/gi,
			            className: 'yellow'
			        }
			    ]
			});
			function myFunction() {
				$('.class-example').highlightWithinTextarea({
				    highlight: [
				        {
				            highlight: 'blueberry',
				            className: 'blue'
				        },
				        {
				            highlight: /ba(na)*/gi,
				            className: 'yellow'
				        }
				    ]
				});
			}
			</script>
		</section>`

Do you see why?

**Comment by lonekorean** [comment]
Instead of destroying/re-initializing the plug-in inside `myFunction()`, try setting it up the highlighting to use a custom function. Then you put whatever logic you need into that custom function (such as using a `currentIndex` variable).

Something like this:

```javascript
function foo(input) {
    return[
        { highlight: otheIndex, className: 'yellow' },
        { highlight: currenIndex, className: 'blue' }
    ];
}

$('.whatever').highlightWithinTextarea({
    highlight: foo
});
```

Check out the Function example on the demo page: https://lonekorean.github.io/highlight-within-textarea/

Whenever that button is clicked that changes `currentIndex`, you can force a highlighting update with this:

```javascript
$('.whatever').highlightWithinTextarea('update');
```

**Comment by MrNHQ** [comment]
Thank you, it works great!
