### ISSUE TITLE
Does it have ReactJs version?

### ISSUE THREAD

**Issue by rathanak-0276** [lonekorean/highlight-within-textarea#36]
This package is awesome. However I want to apply it on my ReactJs project but I don't know how.
So do we have ReactJs version for that?

**Comment by Luchnik** [comment]
+1
same for me

**Comment by Luchnik** [comment]
I found this great package for React
https://www.npmjs.com/package/react-highlight-within-textarea
It serves as a great alternative

**Comment by lonekorean** [comment]
Yep, that's the one. :)
