### ISSUE TITLE
WordPress?

### ISSUE THREAD

**Issue by stevish-com** [lonekorean/highlight-within-textarea#5]
I am trying to use this to highlight certain words on WordPress' "Edit Post" screen. So far, all it does is move the text down by one line, and doesn't highlight anything. Any tips? Could it be because the textarea is sized dynamically?

**Comment by lonekorean** [comment]
Hm, quite possibly. Tried a quick test to resize it via dev tools, I was able to make it become misaligned, but as soon as I edit the text it snaps back in place. Does the same thing happen for you?
