### ISSUE TITLE
How can I clear and delete the highlight

### ISSUE THREAD

**Issue by kelvinfixx** [lonekorean/highlight-within-textarea#6]
I ams using angular model to post the form, the value is clear but the highlight remain on the textarea.

how can I clear it, I clear the value using:

```
$('#content').value('');
```
But the textarea is highlighted.

**Comment by lonekorean** [comment]
The highlights update on the input event, which you can manually trigger after clearing. Try this:

`$('#content').val('').trigger('input');`
