### ISSUE TITLE
One character

### ISSUE THREAD

**Issue by graingerkid** [lonekorean/highlight-within-textarea#7]
Hey, 

Great project, however, I'm having some issues, I seem to be one character out when highlighting...

Do you know what might cause it? Basically, highlighting Peru would highlight 'eru '

**Comment by lonekorean** [comment]
Do you have it up somewhere to take a look at? Or the code/regex you're using for the highlight?

**Comment by graingerkid** [comment]
Sure... http://staging.ontailapp.com/content

**Comment by lonekorean** [comment]
Something in your CSS/Less is adding `padding: 0.2em` to &lt;mark&gt;. That's the tag that this plugin uses to highlight text, so the extra padding is pushing things out of alignment. Override that style back to 0 padding and you should be fine.

**Comment by graingerkid** [comment]
You beauty - thanks mate :)
