### ISSUE TITLE
Compatibility with TinyMCE?

### ISSUE THREAD

**Issue by graingerkid** [lonekorean/highlight-within-textarea#8]
Hey, 

Do you know how I can get this to work alongside tinyMCE (https://www.tinymce.com/download/)?

**Comment by lonekorean** [comment]
Absolutely no idea. :)

Those sorts of editors tend to do a lot of really custom tricky things behind the scenes, far beyond the scope of hijacking a single textarea. Never say never, but I don't plan on doing TinyMCE integration any time soon.
