### ISSUE TITLE
Text slightly off from highlight

### ISSUE THREAD

**Issue by jss367** [lonekorean/highlight-within-textarea#9]
When I run this the highlighting continues for an extra half a character. It is most noticeable when I have several highlighted words in the same line because after say, four, highlighted words the highlighting of the fifth word begins two characters late and ends two and a half characters into the next word. It's possible that I'm doing something wrong but I was curious if anyone else has seen this.

**Comment by lonekorean** [comment]
My hunch is that you have CSS adding padding/margin to &lt;mark&gt; elements (this throws off the highlight alignment). Beyond that, hard to debug without providing some code. :)

**Comment by jss367** [comment]
Ah, thanks for the tip. It looks like in conflicts with Bootstrap, but once I disabled that it works well. Thanks.

**Comment by mastasky** [comment]
Could you let me know how you fixed it? I can't seem to get it to work. Thanks!

**Comment by jss367** [comment]
Unfortunately, I wasn't able to fix the spacing and continue using Bootstrap. The only way I got it to work was after I completely disabled Bootstrap.

**Comment by lonekorean** [comment]
Hi @jss367 and @mastasky. Just pushed an update (v1.0.5) that should resolve this conflict with Bootstrap. Please reopen if not!

**Comment by mastasky** [comment]
Works well! Thanks!
